# Generated by Django 6.0.3 on 2026-03-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_nigerian',
            field=models.BooleanField(default=True),
        ),
    ]
